# Generated by Django 3.2 on 2021-04-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('age', models.IntegerField(max_length=2, verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('released', models.DateField(verbose_name='Año de lanzamiento')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.actor', verbose_name='Actores')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'db_table': 'pelicula',
            },
        ),
    ]
