# Generated by Django 3.2 on 2021-04-29 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='details', verbose_name='Imagen')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.movie', verbose_name='Pelicula')),
            ],
            options={
                'verbose_name': 'Imagenes de la pelicula',
                'verbose_name_plural': None,
                'db_table': 'imagenes',
            },
        ),
    ]
